### ISSUE TITLE
칭호 및 도전과제 관련 기능 작성

### ISSUE THREAD

**Issue by MinseokGo** [Step3-kakao-tech-campus/Team2_BE#17]
# Description
* 도전과제 조회 API를 작성합니다.
* 도전과제 진행률 업데이트 서비스 로직을 구현합니다.
* 칭호 조회 API를 작성합니다.
* 칭호 변경 API를 작성합니다.

# Tasks

- [x] 도전과제 조회 API 작성
- [x] 도전과제 진행률 업데이트 서비스 로직
- [x] 칭호 조회 API
- [x] 칭호 변경 API
- [x] 예외 처리 및 테스트
