### ISSUE TITLE
앨범 멤버 관련 기능 작성

### ISSUE THREAD

**Issue by Choi-Jungbin** [Step3-kakao-tech-campus/Team2_BE#22]
## Description
앨범 멤버에 대한 기능 구현
- 특정 앨범 멤버를 조회한다.
- 특정 앨범 멤버를 추가한다.
- 특정 앨범에서 탈퇴한다.

## Tasks
- [x] 앨범 멤버 조회 기능
- [x] 앨범 멤버 추가 기능
- [x] 앨범 멤버 탈퇴 기능 

## References
