### ISSUE TITLE
피드백 관련 부분 수정

### ISSUE THREAD

**Issue by ki-met-hoon** [Step3-kakao-tech-campus/Team2_BE#39]
## Description

4주차 피드백 부분 수정

## Tasks
- [x] 사용하지 않는 주석 삭제
- [ ] 와일드 카드<?> 표기를 구체적인 response 타입으로 표기
- [x] checkUser method 이름 변경
