### ISSUE TITLE
Swagger 환경 설정

### ISSUE THREAD

**Issue by MinseokGo** [Step3-kakao-tech-campus/Team2_BE#42]
## Description
Swagger 문서 작업을 위한 환경 설정

## Tasks
- [x] Swagger 라이브러리 등록
- [x] Swagger Config 작성
- [x] Swagger 사용을 위한 Security Context 등록
- [x] Swagger path matcher 변경을 위한 yml 작성
