### ISSUE TITLE
앨범 페이지 조회 기능

### ISSUE THREAD

**Issue by MinseokGo** [Step3-kakao-tech-campus/Team2_BE#62]
## Description
앨범 페이지 조회 기능을 작성합니다.

## Tasks
- [x] 앨범 페이지 조회 서비스 작성
- [x] 앨범 페이지 조회 컨트롤러 작성
- [x] 앨범 페이지 조회 DTO 작성
